### ISSUE TITLE
Missing bios files

### ISSUE THREAD

**Issue by DennisLindblom71** [jaspersiebring/libretro_finder#12]
I like your tool but it seems it misses some bios files eg 7800 BIOS (E).rom, 7800 BIOS (U).rom, bas13.rom, BS-X (En) (DRM-Free).bin, BS -X (En).bin, coco3.rom, coco3p.rom, d32.rom, extbas11.rom, TI-994A.ctg, vMac.ROM,

**Comment by jaspersiebring** [comment]
Thanks! Hmm, that's surprising considering that we get all BIOS names and their respective hashes directly [from Libretro's system.dat](https://github.com/jaspersiebring/libretro_finder/blob/main/config/__init__.py). Have you used these BIOS files with RetoArch (and for what cores)?

**Comment by DennisLindblom71** [comment]
If you look in https://raw.githubusercontent.com/libretro/libretro-database/master/dat/System.dat you can see that the files are there.

But maybe they are not needed?

**Comment by jaspersiebring** [comment]
I was able to spend some time on this today and found two issues.

Firstly, the following BIOS files are not in system.dat or any other .dat files in the `libretro-database` repository (main branch; also checked with different extensions and capitalization):
- bas13.rom
- coco3.rom
- coco3p.rom
- d32.rom
- extbas11.rom
- TI-994A.ctg
- vMac.ROM

I want to refrain from diverging from libretro's own system.dat (i.e. I won't manually add them as additional entries, at least not now) but I am still wondering if you used these BIOS files with RetroArch?
  
The other four files however are in system.dat but were not picked up by `libretro_finder` for some reason:
- 7800 BIOS (E).rom
- 7800 BIOS (U).rom
- BS-X (En) (DRM-Free).bin
- BS-X (En).bin

This turned out to be the fault of the regex expression that we use to parse system.dat. It didn't accept quoted 'name' values with spaces or keys in different orders (e.g.  MacII.ROM).

I will be tackling this in a separate branch which will automatically close this issue after a succesful merge. Many thanks for the feedback, wouldn't have found this otherwise!

**Comment by jaspersiebring** [comment]
Just to clarify, that means that we previously "only" searched for 353 of the 357 BIOS files. The regex fix should ensure that we look for everything that Libretro references themselves (all 357 files).

**Comment by jaspersiebring** [comment]
@DennisLindblom71  

Last follow-up, I manually downloaded the aforementioned 4 BIOS files and used [the latest standalone release ](https://github.com/jaspersiebring/libretro_finder/releases)to verify that they can now be found:

![image](https://github.com/jaspersiebring/libretro_finder/assets/25051531/f2415324-8451-49f6-904a-4eaff1796896)

Again, thanks for your feedback! Closing issue.
